name: lumide_api
description: Host API for Lumide IDE plugins. Provides abstractions for plugin development.
version: 1.7.0
homepage: https://lumide.dev
repository: https://github.com/SoFluffyOS/lumide_api

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  json_rpc_2: ^4.1.0
  stream_channel: ^2.1.4
  yaml: ^3.1.3

dev_dependencies:
  test: ^1.25.0
  lints: ^6.0.0
